### ISSUE TITLE
Can this be updated for 20.1 erlang and 1.5 elixir

### ISSUE THREAD

**Issue by shifters67** [joakimk/rpi-elixir#3]
Hi,

very interesting dockerfile - do you intend to update it so that it runs the latest versions of elixir and erlang?  If not i take it we just modify the version in the docker file and make it on the pi?

Ditto the raspberry pi 3 question!  

Just bought a bitscope quatro to start testing docker clusters and of course want to do it with elixir :-)

regards

shifters

**Comment by joakimk** [comment]
I don't actively maintain this, but if you want to please do update rpi-erlang and rpi-elixir and make pull requests in case anyone else wants to use this too.

**Comment by joakimk** [comment]
Any raspberry pi should work as long as the linux distro runs docker. 

- Distro I used: http://blog.hypriot.com/downloads/
- The base image (used by rpi-erlang and rpi-elixir in turn) seems up to date, 4 days ago. https://hub.docker.com/r/resin/rpi-raspbian/
